import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

import "./globals.css";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${sans.className} antialiased`}>
        <div>
          <Header />

          <main className="pt-navigation-height bg-page-gradient relative">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
